Repository artivis/manif, pull requests merged in 2020-08, with the labels that each got.

#153 Add operator scalar * tangent
  include/manif/impl/tangent_base.h
  test/common_tester.h
Labels: API, enhancement

#149 Fix Windows compilation
  CMakeLists.txt
Labels: bug

#157 Fix undesired compile options when gcc is used
  CMakeLists.txt
  examples/CMakeLists.txt
  test/CMakeLists.txt
Labels: bug

#158 Increase CI timeout on arm64 job
  .travis.yml
Labels: enhancement
