Repository artivis/manif, pull requests merged in 2021-03, with the labels that each got.

#206 Add GitHub Actions workflow for Visual Studio
  .github/workflows/ci.yml
Labels: enhancement

#213 Fix/cppcheck 1.90
  CMakeLists.txt
  examples/se2_DeCasteljau.cpp
  examples/se2_interpolation.cpp
  examples/se2_localization_ukfm.cpp
  examples/se2_points_generator.h
  examples/se2_sam.cpp
  examples/se3_sam.cpp
  examples/se3_sam_selfcalib.cpp
Labels: bug

#211 [manifpy] General improvements in SO3 and SE3 objects
  include/manif/impl/so3/SO3_base.h
  python/bindings_se3.cpp
  python/bindings_so3.cpp
  test/python/test_se3.py
  test/python/test_so3.py
  test/so3/gtest_so3.cpp
Labels: API, enhancement

#217 Fixes for float support
  .gitignore
  include/manif/constants.h
  include/manif/impl/eigen.h
  include/manif/impl/se3/SE3Tangent_base.h
  include/manif/impl/se3/SE3_base.h
  include/manif/impl/se_2_3/SE_2_3Tangent_base.h
  include/manif/impl/se_2_3/SE_2_3_base.h
  include/manif/impl/so3/SO3Tangent_base.h
  include/manif/impl/so3/SO3_base.h
  test/common_tester.h
  test/eigen_gtest.h
  test/so3/gtest_so3.cpp
Labels: bug

#214 Set project version
  CMakeLists.txt
  examples/CMakeLists.txt
  package.xml
  python/CMakeLists.txt
  setup.py
  test/CMakeLists.txt
Labels: enhancement
